### ISSUE TITLE
tour: bug in output

### ISSUE THREAD

**Issue by AppzA7** [golang/tour#221] opened 2017-05-16 06:56 UTC
Context: https://tour.golang.org/concurrency/6

//code attached
/*---------------------------------------------------------*/
```golang
package main

import (
	"fmt"
	"time"
)

func main() {
	tick := time.Tick(100 * time.Millisecond)
	boom := time.After(500 * time.Millisecond)
	a := 0
	for {
		a++
		//fmt.Println("outside the select : ", a) /// ------ (1)
		select {
		case <-tick:
			fmt.Println("tick.", a)
		case <-boom:
			fmt.Println("BOOM!", a)
			return
		default:
			fmt.Println("    .", a)
			time.Sleep(50 * time.Millisecond)
		}
		//fmt.Println("outside the select : ", a) /// -------(2)
	}
}
```
/*----------------------------------------------------------------*/

Output snippet : (1) commented,  (2) not commented  --  2 iterations missing

/*----------------------------------------------------------------*/
    . 1
outside the select :  1
    . 2
outside the select :  2
tick. 4
outside the select :  4
    . 5
outside the select :  5
    . 6
outside the select :  6
tick. 8
outside the select :  8
    . 9
outside the select :  9
//////////////////////////////////////////////////////////////////////////////////////////////

Output snippet : (1) not commented,  (2) commented 

/*----------------------------------------------------------------*/
outside the select :  1
    . 1
outside the select :  2
    . 2
outside the select :  3
tick. 3
outside the select :  4
    . 4
outside the select :  5
    . 5
outside the select :  6
tick. 6
outside the select :  7
    . 7
outside the select :  8
    . 8
outside the select :  9
tick. 9
//////////////////////////////////////////////////////////////////////////////////////////////
when line (1) is uncommented and line (2) is commented, 'a' values are printed from 1 to the end.
if (1) is commented and (2) is not, then it skips output of some iterations at a regular interval.

The problem does not happen on the compiler i have on the mac, just on the online one.

Cheers

**Comment by ALTree** [comment] 2018-07-04 09:35
I tried your snippet on the online version of the tour and I couldn't reproduce the issue. Since this issue is quite old and I no longer can reproduce the problem, I'm closing this issue.

**Closed by ALTree** 2018-07-04 09:35 UTC
