### ISSUE TITLE
tour: No output is printed

### ISSUE THREAD

**Issue by swingingsimian** [golang/tour#964] opened 2020-04-29 14:11 UTC
Context: http://127.0.0.1:3999/basics/4

Running the 'basics' examples locally shows no Println output, only `Program exited: signal: killed`. 

Terminal output:
```
14:49 $ ~/go/bin/tour
2020/04/29 14:50:00 Serving content from /Users/nathanjohnson/go/src/golang.org/x/tour
2020/04/29 14:50:00 A browser window should open. If not, please visit http://127.0.0.1:3999
2020/04/29 14:50:03 accepting connection from: 127.0.0.1:56192
2020/04/29 15:01:39 running snippet from: 127.0.0.1:56192
2020/04/29 15:01:51 running snippet from: 127.0.0.1:56192
2020/04/29 15:02:03 running snippet from: 127.0.0.1:56192
2020/04/29 15:02:09 running snippet from: 127.0.0.1:56192
2020/04/29 15:02:28 running snippet from: 127.0.0.1:56192
2020/04/29 15:02:30 running snippet from: 127.0.0.1:56192
2020/04/29 15:03:09 running snippet from: 127.0.0.1:56192
```

This is running on macos, with go installed via brew:
```
$ go version
go version go1.14.2 darwin/amd64
```

**Comment by widyakumara** [comment] 2020-07-27 09:07
Duplicate of #866

**Comment by ALTree** [comment] 2020-09-08 12:25
Caused by server issues, now fixed. Closing here.

**Closed by ALTree** 2020-09-08 12:25 UTC
