### ISSUE TITLE
tour: Slices - wrong 

### ISSUE THREAD

**Issue by llousada** [golang/tour#264] opened 2017-07-14 11:35 UTC
Context: http://127.0.0.1:3999/moretypes/7

	**var s []int = primes[0:6]**

This selects a half-open range which includes the first element, but excludes the last one.
wrong - it includes the elements setted in array,  from 0 to x
The following expression creates a slice which includes elements 1 through 3 of a:

a[1:4]
wrong
if its 1 2 3 4 5 inside the array
is would show
2 3 4
because 1 is the 0 position
and it does not include 4 in 1:4 .. just 1to3

**Comment by ALTree** [comment] 2018-06-29 11:48
> includes elements 1 through 3 of a

It means "the elements in position 1 to 3"

Closing here, since it's working as intended.

**Closed by ALTree** 2018-06-29 11:48 UTC
