### ISSUE TITLE
tour: Type assertions page's (methods/15) code are wrong in english version

### ISSUE THREAD

**Issue by main** [golang/tour#292] opened 2017-09-01 06:35 UTC
Context: https://tour.golang.org/methods/15

https://tour.golang.org/methods/15 has wrong code in english version of tour

**Comment by ALTree** [comment] 2018-06-29 12:34
The code says it'll panic:

```
f = i.(float64) // panic
```

working as intended, closing here.

**Closed by ALTree** 2018-06-29 12:34 UTC
