### ISSUE TITLE
tour: Run Error

### ISSUE THREAD

**Issue by MasihAkbari** [golang/tour#113] opened 2016-11-19 08:18 UTC
Context: https://tour.golang.org/methods/25

running this example cause this error:

> tmp/sandbox589353999/main.go:9: cannot use m (type Image) as type image.Image in argument to pic.ShowImage:
	Image does not implement image.Image (missing At method)

**Comment by Numbluk** [comment] 2016-11-22 05:44
Note that this is an "Exercise". You are meant to fix or add something within the given code sample in order for it to run properly; it should not run with just the sample included. This is not an issue with the Tour.

**Comment by ALTree** [comment] 2018-06-28 12:44
Yes, this is on purpose to show what error you'll see for a mismatch in the interface implementer. Closing, since it's not a bug.

**Closed by ALTree** 2018-06-28 12:44 UTC
