### ISSUE TITLE
tour: [Initialize an array by a default value]

### ISSUE THREAD

**Issue by shivendra-it** [golang/tour#50] opened 2016-07-22 05:20 UTC
Like an array of size 100 filled with value -1 in C++.
eg: **std::fill_n(array, 100, -1);**

The same thing I want to do in Go.

array := make([]int, 100)

how to fill it with -1 in one line?

**Comment by ALTree** [comment] 2018-06-28 13:10
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-06-28 13:10 UTC
