### ISSUE TITLE
tour: Link of concurrency slide not working

### ISSUE THREAD

**Issue by Shenouda-Fawzy** [golang/tour#1078] opened 2020-11-16 16:29 UTC
Context: https://tour.golang.org/concurrency/11

In this paragraph 

> To further explore Go's concurrency model, watch Go Concurrency Patterns (slides) and Advanced Go Concurrency Patterns (slides) and read the Share Memory by Communicating codewalk.

This link https://talks.golang.org/2012/concurrency.slide (**Slide**) in which should points to concurrency slide doesn't work properly it gives me `unexpected EOF`

**Comment by ALTree** [comment] 2020-11-17 09:56
Thanks for reporting this. The issue is being tracket at golang/go#42572. Closing here as a dup.

**Closed by ALTree** 2020-11-17 09:56 UTC
