### ISSUE TITLE
tour: Intentional runtime error in page 5 of chapter "Flow Control Statements..."?

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [golang/tour#521] opened 2018-06-14 01:16 UTC
Context: https://tour.golang.org/flowcontrol/5

Expected:
Code should give the positive squareroot when parameter x is negative.

Actual behaviour:
Code throws a "runtime: out of memory" because of the line 
`return sqrt(-x) + "i"`

Question:
What was the intented purpose of `+"i"`?
I can't see one, as I'm only starting to learn the language, so it's maybe a deprecated feature?

**Comment by bgadrian** [comment] 2018-06-14 21:20
I think the "i" stands for the [imaginary number](https://en.wikipedia.org/wiki/Imaginary_number), it is not a feature of Go. 
As stated [in docs](https://golang.org/pkg/math/#Sqrt) sqrt of a negative number is NaN, so maybe the code should be `math.Sqrt(-1*x)` ?

**Comment by JackLeEmmerdeur** [comment] 2018-06-16 18:13
Thanks for pointing out the topic of imaginary numbers. I'm no maths-buff, but I guess it should be general knowledge. I vaguely remember that every number has a positve and negative squareroot. I guess it's up to oneself to delve into the explanation of why sqrt(-4) will result in 2i an imaginary number. I also installed go in my machine and tested the mentioned code. Can't explain the "out of memory" in playground, other than the code somehow gets into an infinite recursion, but I can't see a reason why.

**Comment by bgadrian** [comment] 2018-06-16 18:15
Out of memory is random server error and occurs to any page.

It seems a duplicate of https://github.com/golang/tour/issues/512

**Comment by JackLeEmmerdeur** [comment] 2018-06-16 18:22
Hmm yes, but it throws reproducible on that code and I guess it could irritate beginners, as the go lang tour is maybe the first place they start at learning. For my part, you can close this issue. I'll use my local installation for testing the code in future. Thanks for the help.

**Comment by bgadrian** [comment] 2018-06-16 18:51
@JackLeEmmerdeur with welcome, and I agree that it is a spiny problem, I hope someone will investigate it.

I cannot close the ticket, I have no rights, I'm just a random fan around here.

**Comment by ALTree** [comment] 2018-07-11 08:08
Closing here since we're tracking the out-of-memory issue in #512

**Closed by ALTree** 2018-07-11 08:08 UTC
