### ISSUE TITLE
`go tool` does not have `tour` option 

### ISSUE THREAD

**Issue by NorikDavtian** [golang/tour#160] opened 2017-02-05 08:53 UTC
Context: https://tour.golang.org/welcome/3
`go version go1.7.5 darwin/amd64`

possible options when running `go tool` return
```bash
addr2line
api
asm
cgo
compile
cover
dist
doc
fix
link
nm
objdump
pack
pprof
trace
vet
yacc
```

**Comment by alebaffa** [comment] 2017-04-04 20:29
`go tool tour` is now available in go1.8. This issue can be closed.

**Comment by robphoenix** [comment] 2017-06-06 16:12
duplicate of https://github.com/golang/tour/issues/8

@NorikDavtian If you feel this issue is addressed there please considered closing it, thanks!

**Comment by ALTree** [comment] 2018-07-04 09:46
Yep, closing as a dup of #8.

**Closed by ALTree** 2018-07-04 09:46 UTC
