### ISSUE TITLE
tour: "does what you'd expect" is not helpful

### ISSUE THREAD

**Issue by eythian** [golang/tour#127] opened 2016-12-20 14:09 UTC
Context: https://tour.golang.org/moretypes/2

The description is:

    A struct is a collection of fields.
    
    (And a type declaration does what you'd expect.) 

I think that having "does what you'd expect" in a tutorial isn't wise, given you don't know what people expect, or what their experience of a C-like language is. I think it should be replaced with something that explains what it actually does.

**Comment by michaelorr** [comment] 2017-02-06 19:34
This is noted as a confusing point for people new to Go or to statically typed languages. https://twitter.com/polotek/status/827570862819725313
I think we can do better.

**Comment by zombiezen** [comment] 2017-03-13 18:35
@broady This is a dupe of #121

**Comment by ALTree** [comment] 2018-06-28 15:59
Closing as a dup of #121

**Closed by ALTree** 2018-06-28 15:59 UTC
