### ISSUE TITLE
18/27 slices go tutorial build failed

### ISSUE THREAD

**Issue by Nikola-Milovic** [golang/tour#987] opened 2020-06-11 10:52 UTC
On Xiaomi A9 Android 10 the above mentioned exercise fails

**Comment by ALTree** [comment] 2020-06-11 11:00
Hi,

it's an exercise. The title says **Exercise: Slices** and the first sentence in the text is

> Implement Pic.

Before you do that, it won't compile. 

Closing here, as this is working as intended.

**Closed by ALTree** 2020-06-11 11:00 UTC
