### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by ngnam** [golang/tour#924] opened 2020-03-16 11:38 UTC
This is my code javascript:
```
var firstMissingPositive = function(nums) {
    var swap = function(i, j) {
        var tmp = nums[i];
        nums[i] = nums[j];
        nums[j] = tmp;
    };

    for (let i = 0; i < nums.length; i++) {
        while (0 < nums[i] && nums[i] - 1 < nums.length
                && nums[i] != i + 1
                && nums[i] != nums[nums[i] - 1]) {
            swap(i, nums[i] - 1);
        }
    }

    for (let i = 0; i < nums.length; i++) {
        if (nums[i] != i + 1) {
            return i + 1;
        }
    }

    return nums.length + 1;
};
```
i wanna convert to .go. so help me! thak you

Context: https://tour.golang.org/welcome/1
```
package main

import "fmt"

func main() {
	s := []int{2, 3, 5, 7, 11, 13}
	fmt.Println(firstMissingPositive(s))
}

func firstMissingPositive(nums []int) {
	var swap = func(i int, j int) {
		var tmp = nums[i]
		nums[i] = nums[j]
		nums[j] = tmp
	}

	for i := 0; i < len(nums); i++ {
		for 0 < nums[i] && nums[i]-1 < len(nums) && nums[i] != i+1 && nums[i] != nums[nums[i]-1] {
			swap(i, nums[i]-1)
		}
	}

	for i := 0; i < len(nums); i++ {
		if nums[i] != i+1 {
			return i + 1
		}
	}

	return len(nums) + 1
}
```

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by ALTree** [comment] 2020-03-16 12:31
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-03-16 12:31 UTC
