### ISSUE TITLE
ERROR IN THE EXAMPLE CODE!  #rand.Seed.Intn undefined (type func(int64) has no field or method Intn)

### ISSUE THREAD

**Issue by sherzon** [golang/tour#607] opened 2018-09-17 05:40 UTC
Context: https://tour.golang.org/basics/1

There is a mistake in the code that is given in the Golang tour page example.
Instead of  `rand.Intn()`  it is showing  `rand.Seed.Intn() `.
Please check and rectify the problem.
On resetting the code it will change back to the correct form.
 
![screenshot from 2018-09-17 10-40-58](https://user-images.githubusercontent.com/41055719/45607315-364abc00-ba69-11e8-855e-5a68fb27e968.png)

**Comment by bgadrian** [comment] 2018-09-21 12:52
Please use an incognito window or clear your local storage. 

You have that code in local browser cache and is wrong, the live code does not have that problem: https://github.com/golang/tour/blob/master/content/basics/packages.go

If the problem is fixed do not forget to close the issue! Thanks.

**Comment by ALTree** [comment] 2018-09-23 08:27
Yeah, this is a client-side cache issue. You (or someone using the browser you're using) changed the code while experimenting. Closing here.

**Closed by ALTree** 2018-09-23 08:27 UTC
