### ISSUE TITLE
tour: fatal error runtime out of memory

### ISSUE THREAD

**Issue by seanjmee** [golang/tour#525] opened 2018-06-17 03:46 UTC
Context: https://tour.golang.org/flowcontrol/5

Clicking on 'Run' causes the error above to be displayed in the console window.

**Comment by bgadrian** [comment] 2018-06-17 07:40
there are other reports of "Out of memory" and "cannot allocate memory" errors
I think is a duplicate of https://github.com/golang/tour/issues/512

**Comment by yoavmmn** [comment] 2018-06-18 21:59
I've experienced the same problem.
Ironically, adding parentheses to the `if` statement works just fine.

```go
package main

import (
	"fmt"
	"math"
)

func sqrt(x float64) string {
	if (x < 0) {
		return sqrt(-x) + "i"
	}
	return fmt.Sprint(math.Sqrt(x))
}

func main() {
	fmt.Println(sqrt(2), sqrt(-4))
}
```

**Comment by AidySun** [comment] 2018-06-21 03:32
I got the same error. The strange thing is that following code changes didn't have the error.
1. change print order or number in main
`
func main() {
        fmt.Println(sqrt(2), sqrt(-4))
	fmt.Println(sqrt(-4), sqrt(2))
	fmt.Println(sqrt(4), sqrt(-2))
	fmt.Println(sqrt(-2), sqrt(4))
	fmt.Println(sqrt(2))
	fmt.Println(sqrt(-4))
}
`
2. just add an empty comment line at the beginning of sqrt()
`
func sqrt(x float64) string {
	// 
	if x < 0 {
		return sqrt(-x) + "i"
	}
	return fmt.Sprint(math.Sqrt(x))
}

func main() {
	fmt.Println(sqrt(2), sqrt(-4))
}
`

Does server have some hard-code or cache specified for the default example code?

**Comment by AidySun** [comment] 2018-06-21 03:40
Any changes to the default code, even adding one space, would get rid of the exception.

**Comment by bgadrian** [comment] 2018-06-21 06:11
Yes, from what I can see the original source code (when the page is loaded) has some invalid unicode characters.

**Comment by ALTree** [comment] 2018-08-11 10:46
> Any changes to the default code, even adding one space, would get rid of the exception.

That's because the output is cached using the hash of the source. Changing one char will bypass the bad cached entry.

Closing as a dup of  #541

**Closed by ALTree** 2018-08-11 10:46 UTC
