### ISSUE TITLE
tour: Bug in last varible, or am I missing something?

### ISSUE THREAD

**Issue by BC2A** [golang/tour#953] opened 2020-04-19 18:17 UTC
Context: https://tour.golang.org/basics/8

watch the value ten(10) at end of line...
var c, python, java = true, false , 10      is NO worky
BUT:
var c, python, java = true, false ,10       OK is worky! ( ie without space )
ALSO:
var c, python, java = true, 10 , false      Is also worky! ( ie with a space but not last / at end of line)

**Comment by ALTree** [comment] 2020-04-19 18:33
Hi, there's no `10` in the code at https://tour.golang.org/basics/8. If you see one, it was probably modified locally on that browser by you or something else using the same machine.

Also please note that the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-04-19 18:33 UTC
