### ISSUE TITLE
Ambiguous output between online and local compiler

### ISSUE THREAD

**Issue by Anudeep-Mad** [golang/tour#814] opened 2019-09-05 03:33 UTC
Context: https://tour.golang.org/moretypes/15

According to the documentation of slices in Golang, whenever the length and capacity of a slice is same and a new append function is made on it, The capacity defaultly increases. And the code from the tutorial is showing two different outputs when executed online vs executed locally. 

Tutorial output: 

![image](https://user-images.githubusercontent.com/9420883/64309921-3985d300-cf6c-11e9-9273-c09aad2da00f.png)

Compiler Output when executed locally

![image](https://user-images.githubusercontent.com/9420883/64309955-55897480-cf6c-11e9-9d0b-0cb9dc3043d2.png)

**Comment by ALTree** [comment] 2019-09-10 09:13
This is working as intended. The specification does not say how much the slice should grow. The current implementation handles growing in different ways between 32 and 64 bit architectures. The tour runs on a 32bit platform, your machine is likely 64bit. Closing here.

**Closed by ALTree** 2019-09-10 09:13 UTC
