### ISSUE TITLE
tour: If dropping the first two, any way to get it back? 

### ISSUE THREAD

**Issue by zhonglzli** [golang/tour#361] opened 2017-12-11 02:39 UTC
Context: https://tour.golang.org/moretypes/11

Change the title above to describe your issue and add your feedback here, including code if necessary

package main

import "fmt"

func main() {
	s := []int{2, 3, 5, 7, 11, 13}
	printSlice(s)

	// Drop the first two
	s = s[2:]
	printSlice(s)

	// Anyway to get the first two back?
	s = s[-2:]
	printSlice(s)
}

func printSlice(s []int) {
	fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}

**Comment by bgadrian** [comment] 2018-06-17 17:06
No, you cannot move the header of the slice in reverse. 
One way to achieve what you are looking for (only way I know) is by keeping a copy of the original slice.

**Comment by ALTree** [comment] 2018-06-28 13:11
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-06-28 13:11 UTC
