### ISSUE TITLE
tour: Slice defaults, typo slice -> array?

### ISSUE THREAD

**Issue by vabr-g** [golang/tour#449] opened 2018-03-31 13:31 UTC
Context: https://tour.golang.org/moretypes/10

When the text says: "The default [slice bound] is [...] the length of the _slice_ for the high bound," should it say "the length of the _array_" instead? It is not clear what a length of a slice is.

**Comment by bgadrian** [comment] 2018-06-27 22:16
The sentence "The default is zero for the low bound and the length of the slice for the high bound." is also discussed/duplicate of https://github.com/golang/tour/issues/182

**Comment by ALTree** [comment] 2018-07-04 10:17
Closing here as a dup of #182. Let's keep the discussion there.

**Closed by ALTree** 2018-07-04 10:17 UTC
