### ISSUE TITLE
tour: [Clicking "Run" on any of the exercises returns the error "Error communicating with remote server." rather than running the code]

### ISSUE THREAD

**Issue by semlimi-ie** [golang/tour#1293] opened 2021-12-06 16:34 UTC
Clicking "Run" on any of the exercises returns the error "Error communicating with remote server." rather than running the code

I've been seeing this issue for over a week now where if I click the "Run" button it returns "Error communicating with remote server." rather than executing the code for every Go exercise I've tried. I've tried it on both Chrome and firefox browsers and same error. And on the console it shows this error when I click Run - "https://go.dev/_/compile?backend=undefined 500"

**Comment by CalRobert** [comment] 2021-12-06 16:40
Just a note that I have the same issue.

**Comment by shashankkatte** [comment] 2021-12-06 17:41
Another confirmation

I see the same issue.

**Comment by stmllr** [comment] 2021-12-06 20:19
Duplicate of #1288
Fix seems to be on the way

**Comment by ALTree** [comment] 2021-12-07 17:22
Fix should be deployed, closing here.

**Closed by ALTree** 2021-12-07 17:22 UTC
