### ISSUE TITLE
tour: Build failed for Go Playground

### ISSUE THREAD

**Issue by kimprice** [golang/tour#1326] opened 2022-03-16 13:15 UTC
Context: https://go.dev/tour/basics/11

![image](https://user-images.githubusercontent.com/15070078/158597548-27aa02ee-0e13-4a2a-a798-e6ddd340d7be.png)

**Comment by kimprice** [comment] 2022-03-16 13:41
It seems to be failing on all the pages. So far none of them have built successfully. It was working a few days ago. Looks like the Go Playground itself is also failing. Maybe this has to do with the 1.18 release?

**Comment by kimprice** [comment] 2022-03-16 13:50
It's running now! :)

**Comment by dmitshur** [comment] 2022-03-16 13:50
Thanks, I'll close this as a duplicate of golang/go#51708.

**Closed by dmitshur** 2022-03-16 13:50 UTC
Labels: NeedsInvestigation
