### ISSUE TITLE
tour: go tool tour does not work

### ISSUE THREAD

**Issue by stefanwalther** [golang/tour#116] opened 2016-11-23 11:03 UTC
Context: https://tour.golang.org/welcome/3

Tool `go tool tour` does not work as expected, just get `go tool: no such tool "tour"`.
(Using `go1.6 darwin/amd64` on OSX)

Solution, just needs to be installed (as described here: https://github.com/golang/tour), but that should be mentioned in the tutorial.

**Comment by cgorshing** [comment] 2017-02-07 17:29
Duplicates at: #160 and #153 

Thanks for posting about the solution.

**Comment by alebaffa** [comment] 2017-04-04 20:28
`go too tour` is now available in go1.8. This issue can be closed.

**Comment by odedpriva** [comment] 2017-04-21 13:12
same issue 
```
➜  pebble git:(master) ✗ go version
go version go1.8.1 darwin/amd64
➜  pebble git:(master) ✗ go tool tour
go tool: no such tool "tour"
```

any idea ?

**Comment by alebaffa** [comment] 2017-04-21 13:24
`go1.8.1 windows/amd64` is fine. So, maybe it's a problem with the OSX installation.

**Comment by InfiniteDevelopment** [comment] 2017-05-11 22:36
tour is not installed by default with an installation of go. You need to go get it:

go get golang.org/x/tour/gotour

Docs: https://github.com/golang/tour/

**Comment by robphoenix** [comment] 2017-06-06 16:12
duplicate of #8

@stefanwalther  If you feel this issue is addressed there please considered closing it, thanks!

**Comment by ALTree** [comment] 2018-06-28 16:02
Closing as a dup of #8

**Closed by ALTree** 2018-06-28 16:02 UTC
