### ISSUE TITLE
tour: run failed in the tour

### ISSUE THREAD

**Issue by yjiangnan** [golang/tour#540] opened 2018-06-27 21:04 UTC
Context: https://tour.golang.org/welcome/4

prog.go:12:2: cannot refer to unexported name time.sleep
prog.go:12:2: undefined: time.sleep

Program exited.

**Comment by bgadrian** [comment] 2018-06-27 22:01
I cannot find Sleep in the example page.

I presume you typed somewhere `time.sleep` instead of `time.Sleep`. Notice the lowercase, it has to be uppercase to access a public/exported structure from a library.

**Comment by ALTree** [comment] 2018-06-28 14:14
Yep, it's `time.Sleep` with capital `S`. Closing here, since it's not a bug.

**Closed by ALTree** 2018-06-28 14:14 UTC

**Comment by ALTree** [comment] 2018-06-29 14:39
AFAIK modified snippets are kept in the browser's LocalStorage. It's up to the user to delete them if necessary.
