### ISSUE TITLE
tour: Is the wanted output wrong? Is the test right?

### ISSUE THREAD

**Issue by DrasiusMajere** [golang/tour#159] opened 2017-02-04 01:01 UTC
Context: https://tour.golang.org/moretypes/23

when you say that a map of the counts of each "word" of the string s is wanted, you mean the length of the word, the amount of characters of each word in that string??

why did the test show this output?

"""
FAIL
 f("I am learning Go!") =
  map[string]int{"I":1, "am":2, "learning":8, "Go!":3}
 want:
  map[string]int{"I":1, "am":1, "learning":1, "Go!":1}
Program exited.

"""

`
func WordCount(s string) map[string]int {
		words := make(map[string]int)
	for _,val := range strings.Fields(s) {
		words[val] = len(val)
	}
	return words
}
`

**Comment by s4astliv** [comment] 2018-01-04 13:47
Probably mistake in the testing code. As soon as you return:

```return map[string]int{"I":1, "am":1, "learning":1, "Go!":1}```

you get the following output:

```PASS
 f("I am learning Go!") = 
  map[string]int{"Go!":1, "I":1, "am":1, "learning":1}
FAIL
 f("The quick brown fox jumped over the lazy dog.") =
  map[string]int{"learning":1, "Go!":1, "I":1, "am":1}
 want:
  map[string]int{"brown":1, "fox":1, "over":1, "the":1, "dog.":1, "The":1, "quick":1, "jumped":1, "lazy":1}
Program exited.```

**Comment by WheeskyJack** [comment] 2018-04-16 04:05
Hi,
The exercise is for finding the number of words in the statement and not for finding number of characters in each word of the statement.  There are multiple statements passed to function for testing; hence hard-coding any specific statement in return value will not solve the problem;it will merely fail in next test case.

BR.

**Comment by ALTree** [comment] 2018-07-04 09:47
What @WheeskyJack said. This is working as intended, so I'm closing this issue.

**Closed by ALTree** 2018-07-04 09:47 UTC
