### ISSUE TITLE
tour: OOM in flowcontrol/5 section (if statement)

### ISSUE THREAD

**Issue by mrampton** [golang/tour#524] opened 2018-06-17 01:26 UTC
Context: https://tour.golang.org/flowcontrol/5

OOM in flowcontrol/5 section
==============
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x5fda69, 0x16)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc420880000, 0x100000, 0x0, 0x7178d8)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x6fef40, 0x100000, 0x7fcf26327980)
	/usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x6fef40, 0x72, 0x0)
	/usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x6fef40, 0x72, 0x7178e8, 0xc42003bee0)
	/usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x6fef40, 0x72, 0x410101, 0xc41ffbc5ff)
	/usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x6fef40, 0x72, 0xc420010101, 0x412e8c)
	/usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0xe3057, 0x440101, 0x7fcf265356c8)
	/usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1175

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc4204ee4d8 sp=0xc4204ee4d0 pc=0x451b50
runtime.mallocgc(0xe3057, 0x5b5220, 0xc4204ee801, 0xe3057)
	/usr/local/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc4204ee578 sp=0xc4204ee4d8 pc=0x40f5c2
runtime.makeslice(0x5b5220, 0xe3057, 0xe3057, 0xffffffffffffffff, 0x400, 0x11)
	/usr/local/go/src/runtime/slice.go:61 +0x77 fp=0xc4204ee5a8 sp=0xc4204ee578 pc=0x43e247
cmd/link/internal/objfile.(*objReader).readSlices(0xc4204ee8a0)
	/usr/local/go/src/cmd/link/internal/objfile/objfile.go:140 +0x49 fp=0xc4204ee5f0 sp=0xc4204ee5a8 pc=0x4f5529
cmd/link/internal/objfile.(*objReader).loadObjFile(0xc4204ee8a0)
	/usr/local/go/src/cmd/link/internal/objfile/objfile.go:113 +0x417 fp=0xc4204ee7e8 sp=0xc4204ee5f0 pc=0x4f5087
cmd/link/internal/objfile.Load(0x6ed460, 0xc420068140, 0xc420018610, 0xc4204d4180, 0x18c3ef, 0xc4204e6180, 0x31)
	/usr/local/go/src/cmd/link/internal/objfile/objfile.go:69 +0x1a1 fp=0xc4204ee9c8 sp=0xc4204ee7e8 pc=0x4f4a61
cmd/link/internal/ld.ldobj(0xc4204cc000, 0xc420018610, 0xc4204d4180, 0x18c48e, 0xc4204e6180, 0x31, 0xc4204da0c9, 0x29, 0x1, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:1515 +0xcb1 fp=0xc4204eec80 sp=0xc4204ee9c8 pc=0x54f611
cmd/link/internal/ld.loadobjfile(0xc4204cc000, 0xc4204d4180)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:839 +0x50d fp=0xc4204eee68 sp=0xc4204eec80 pc=0x548fbd
cmd/link/internal/ld.(*Link).loadlib(0xc4204cc000)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:365 +0x183 fp=0xc4204ef110 sp=0xc4204eee68 pc=0x545a33
cmd/link/internal/ld.Main(0x6ed460, 0x10, 0x20, 0x1, 0x7, 0x10, 0x5ff52f, 0x1b, 0x5fc865, 0x14, ...)
	/usr/local/go/src/cmd/link/internal/ld/main.go:201 +0xa73 fp=0xc4204ef2a0 sp=0xc4204ef110 pc=0x55d4d3
main.main()
	/usr/local/go/src/cmd/link/main.go:62 +0x277 fp=0xc4204eff88 sp=0xc4204ef2a0 pc=0x594ad7
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc4204effe0 sp=0xc4204eff88 pc=0x429f62
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4204effe8 sp=0xc4204effe0 pc=0x454541

**Comment by bgadrian** [comment] 2018-06-17 07:39
there are other reports of "Out of memory" and "cannot allocate memory" errors
I think is a duplicate of https://github.com/golang/tour/issues/512

**Comment by ivanruski** [comment] 2018-06-23 13:17
If you put parentheses around the "if" condition the program works even though the description  says that parentheses are not required. I don't know why

**Comment by ALTree** [comment] 2018-08-11 10:45
Closing as a dup of  #541

**Closed by ALTree** 2018-08-11 10:45 UTC
