### ISSUE TITLE
tour: memory issues

### ISSUE THREAD

**Issue by rickyrattlesnake** [golang/tour#512] opened 2018-06-10 11:53 UTC
Context: https://tour.golang.org/concurrency/4

Attempting to run the sample code, I get this error `/usr/local/go/src/sync/pool.go:9:2: read /usr/local/go/src/runtime/symtab_test.go: read /usr/local/go/src/runtime/symtab_test.go: cannot allocate memory`

**Comment by rickyrattlesnake** [comment] 2018-06-10 11:54
Seems to work ok for channel buffer size < 10

**Comment by bgadrian** [comment] 2018-06-10 13:19
It works for me, even with buffer 100. Please try again later and confirm? Maybe it was a temporary server glitch.

**Comment by ankush981** [comment] 2018-06-15 05:17
Hello! Random contributor here. :smile: 

Doesn't seem to work for me too:

![screenshot from 2018-06-15 10-46-10](https://user-images.githubusercontent.com/4169691/41451216-6c45c6a8-7089-11e8-9430-c14dc8b85452.png)

**Comment by bgadrian** [comment] 2018-06-15 20:58
It seems random, can you try again later? 
More users complain, on different pages at different times.

**Comment by ankush981** [comment] 2018-06-18 11:09
Didn't work again. Can someone check whether the server is actually running out of memory?

**Comment by KraProgrammer** [comment] 2018-06-18 11:27
I have the same problem, but if i add newline after for loop its working.
![image](https://user-images.githubusercontent.com/32852304/41533519-4ab9d168-72fb-11e8-9282-c9456976de68.png)

**Comment by bgadrian** [comment] 2018-06-18 11:39
It's random, probably there are many containers (servers) that receive the Run calls, and some of them remain out of memory, depending on the online users probably. 
I posted the issue on the Go developer group, I'm waiting for someone to investigate it (who has access to the production env).

**Comment by ankush981** [comment] 2018-06-18 12:11
Talk about crazy! @bgadrian I can verify that adding a newline after the loop (as indicated by @KraProgrammer) indeed works. Weird, eh?

**Comment by bgadrian** [comment] 2018-06-18 12:21
Ah yes, I forgot, I discovered a difference between calls here https://github.com/golang/tour/issues/505 

When you load the page for the first time, it loads (in the textarea) a bugged source code.
Any modification you do, like adding a new line, "it fixes" some invalid, invisible characters.
The issue is that the code is remembered in your browser, so to reproduce it you have to use a private browser session.

**Comment by bgadrian** [comment] 2018-06-18 15:15
My guess is that it is a tour thing, if it was a bigger problem (related to the Go language) most likely was already fixed. 
**We** have to fix it, noone is in charge of this project, officially. 
I think next week I can find some time to further investigate the issue, hopefully then replicate it on a local env, and then make a pull request.

Hopefully it is something simple, like the source code formatting issue, or some incompatibility between the newer browser versions (most of the tour was not touched since 2-3years ago), or the servers are old and broken :)

**Comment by ALTree** [comment] 2018-08-11 10:46
Closing as a dup of  #541

**Closed by ALTree** 2018-08-11 10:46 UTC
