### ISSUE TITLE
tour: variable x is used but cannot compile!

### ISSUE THREAD

**Issue by sirayliu** [golang/tour#810] opened 2019-08-27 16:45 UTC
Context: https://tour.golang.org/moretypes/18

When I was doing the exercise of slice allocation, I encounter a compilation error:
“./prog.go:11:10: x declared and not used”. But, it doesn’t look like x is not used.

Here is my code.
package main

import "golang.org/x/tour/pic"
//import "fmt"

func Pic(dx, dy int) [][]uint8 {

	mypic := make([][]uint8, dy)
	for i := 0; i < dy; i++ {
		mypic[i] = make([]uint8, dx)
		for j, x := range mypic[i] {
			x = uint8(j)
			//fmt.Print(" ", x)
		}
	}
	return mypic

}

func main() {
	pic.Show(Pic)
}

**Comment by ALTree** [comment] 2019-08-27 16:49
Hi,

assigning to a variable doesn't count as "using". The `x = uint8(j)` line is not using `x`. After all, putting a book in a shelf doesn't not count as using it. You're only using it when you take it out of the shelf and read it.

Closing here, since this is not a bug.

**Closed** 2019-08-27 16:49 UTC
