### ISSUE TITLE
tour: `{` starting in a newline after the function definition results in compilation error

### ISSUE THREAD

**Issue by nastra** [golang/tour#957] opened 2020-04-22 16:02 UTC
Context: http://127.0.0.1:3999/basics/4

Having `{` starting in a newline after the function definition and hitting `Format` results in `prog.go:10:1: unexpected semicolon or newline before {`. Below is the code that reproduces the issue.
```
package main

import "fmt"

func add(x int, y int) int {
	return x + y
}

func main() 
{
	fmt.Println(add(23, 1))
}
```

Hitting `Run` will also show additional details around the compilation error.
```
# command-line-arguments
./compile6.go:9:6: missing function body
./compile6.go:10:1: syntax error: unexpected semicolon or newline before {
```

**Comment by ALTree** [comment] 2020-04-22 16:11
Hi,

not allowed in go. See the "[why can't I put the opening brace on the next line?](https://golang.org/doc/faq#semicolons)" FAQ. Closing here, since this is working as intended.

**Closed by ALTree** 2020-04-22 16:11 UTC

**Comment by nastra** [comment] 2020-04-22 16:21
Gotcha, thanks for clarifying.
