### ISSUE TITLE
tour: fails.

### ISSUE THREAD

**Issue by ken-graham** [golang/tour#851] opened 2019-11-16 21:44 UTC
Context: https://tour.golang.org/moretypes/18

There is nothing else that you need to know.

Execution fails.

**Comment by ALTree** [comment] 2019-11-16 21:55
The linked page is an exercise. The slide title is **Exercise: Slices**, and the text below says:

> Implement Pic. 

so yes, it won't compile until you solve the exercise by implementing the requested function.

Closing here, since this is working as intended.

**Closed by ALTree** 2019-11-16 21:55 UTC
