### ISSUE TITLE
tour: "Numeric Constants" strange results

### ISSUE THREAD

**Issue by JESii** [golang/tour#151] opened 2017-01-28 13:34 UTC
Context: https://tour.golang.org/basics/16
Chrome Version 55.0.2883.95 (64-bit)
OSX 10.11.6

The Numeric Constants example gives strange results with needInt(xxx).

When I modified the code to print 
`	fmt.Printf("Small: %d; needInt(Small): %d\n", Small, needInt(Small))`
what I got was
`Small: 2; needInt(Small): 21`

That certainly seems wrong to me.

More generally, what's the purpose of creating a function called `needInt` which accepts `x  int`, and returns the int value `(x*10 + 1)`?

**Comment by ALTree** [comment] 2018-07-04 09:53
> That certainly seems wrong to me.

Looks correct to me. Small is 2 and the function return 10x+1 which is 21.

> More generally, what's the purpose of creating a function called needInt which accepts x int, and returns the int value (x*10 + 1)?

The point is to show how arguments are passed I think, what the function does doesn't seem too important. It's just an example.

This is working as intended, so I'm closing this issue.

**Closed by ALTree** 2018-07-04 09:53 UTC
