### ISSUE TITLE
tour: %g is not working as expected. 

### ISSUE THREAD

**Issue by jdvala** [golang/tour#828] opened 2019-10-10 13:29 UTC
Context: https://tour.golang.org/basics/2

In the tour I have tried the formatting option using `%g` but for me it it not working.

```go
package main

import (
	"fmt"
	"math/rand"  //this is similar in python as "from math import rand"
	"math"
)


/* 

There is no comma between the imports so just write them one by one,

We can also write imports like 
import "fmt"
import "math" 
but its a go convention to factorize the import statements.

*/
func main(){
	fmt.Println("My favorite number is", rand.Intn(10))
	fmt.Println("Now we learn formating with %g.\n", math.Sqrt(9))
}
```

Output:
```bash
My favorite number is 1
Now we learn formating with %g.
 3
```

**Comment by ALTree** [comment] 2019-10-10 13:34
Hi,

you have to use `fmt.Printf` (what the example at https://tour.golang.org/basics/2 does). `fmt.Println` is a different function, which doesn't use the classic `%` flags C programmer are used to.

Closing here, since this is working as intended.

**Closed by ALTree** 2019-10-10 13:34 UTC
