### ISSUE TITLE
A tour of Go @ Appending to a slice

### ISSUE THREAD

**Issue by TokyoWolFrog** [golang/tour#398] opened 2018-01-30 04:46 UTC
### What version of Go are you using (`go version`)?
go1.9.3 

### Does this issue reproduce with the latest release?
I think I'm using the latest release

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
	var s []int
	printSlice(s)

	// append works on nil slices.
	s = append(s, 0)
	printSlice(s)

	// The slice grows as needed.
	s = append(s, 1)
	printSlice(s)

	// We can add more than one element at a time.
	s = append(s, 2,3,4)
	printSlice(s)

### What did you expect to see?
len=0 cap=0 []
len=1 cap=1 [0]
len=2 cap=2 [0 1]
**len=5 cap=5 [0 1 2 3 4]**

### What did you see instead?
len=0 cap=0 []
len=1 cap=1 [0]
len=2 cap=2 [0 1]
**len=5 cap=6 [0 1 2 3 4]**

**Comment by WheeskyJack** [comment] 2018-04-15 14:10
Hi,
the capacity of slice gets doubled in general (for not so large length array) whenever the slice outgrows its current capacity. 
So expected capacity should have been 8 instead of 6 (as printed by code) or 5 (as expected by you).
When 2 is added to the slice, it exceeds its current capacity and new slice with double the capacity is created. So the capacity becomes 4. Next when 3 is added, capacity is not exceeded;hence it remains unchanged. But finally when 4 is appended to slice , its capacity increases the current capacity of 4 and new slice with capacity 8 (double the current capacity of 4) is created.
please refer following blog for more information on slices :
https://blog.golang.org/go-slices-usage-and-internals

BR.

**Comment by ALTree** [comment] 2018-07-02 12:07
As explained above, this is working as intended. Closing here.

**Closed by ALTree** 2018-07-02 12:07 UTC

**Comment by TokyoWolFrog** [comment] 2018-07-02 22:07
Thanks!

**Comment by allenGKC** [comment] 2020-03-19 10:12
@WheeskyJack 
Hi WheeskyJack, I was still confused about s = append(s, 0), after that why cap turns to 2?
is it (cap+1)*2 when cap is 0?
