### ISSUE TITLE
program does not work!

### ISSUE THREAD

**Issue by xakepp35** [golang/tour#869] opened 2019-12-17 17:12 UTC
Consider following code, typed in editor at https://tour.golang.org/

```
package main

import (
	"fmt"
	"time"
)

// main measures remote host os timer precision
func main() {
	t0 := time.Now().UnixNano()
	for {
		t1 := time.Now().UnixNano()
		if t1 != t0 {
			fmt.Println(t1 - t0)
			return
		}
	}
}
```

**Expected output:** int64, somewhere from 1 to approximately 2000000
**Actual output:** Program exited: process took too long.

It could not take too long, if timer is working correctly.
So it seems you do have a bug somewhere. Good luck!

**Comment by ALTree** [comment] 2019-12-17 18:51
Not a bug, see https://tour.golang.org/welcome/4:

>  There are limitations to the programs that can be run in the playground:
>
> In the playground the time begins at 2009-11-10 23:00:00 UTC (determining the significance of this date is an exercise for the reader). This makes it easier to cache programs by giving them deterministic output.

Now() always return the same value. Closing here, since this is working as intended.

**Closed by ALTree** 2019-12-17 18:51 UTC
