### ISSUE TITLE
tour: command didn't work

### ISSUE THREAD

**Issue by danaconda** [golang/tour#396] opened 2018-01-26 16:29 UTC
Context: https://go-tour-ru-ru.appspot.com/welcome/3

$go tool tour # didn't work for me 

go version go1.9.2 linux/amd64
kali linux 
what dependencies i need to install?

**Comment by bgadrian** [comment] 2018-06-27 21:40
None, it should work, but you can install it manually see the notes

> To run the tour locally first download and install Go then start the tour from the command line:
> go tool tour
Or, you can install and run this tour manually if you have any trouble running the above command:
go get golang.org/x/tour/gotour
gotour

Duplicate of #8 I think

**Comment by ALTree** [comment] 2018-07-02 12:08
Closing as a dup of #8.

**Closed by ALTree** 2018-07-02 12:08 UTC
