### ISSUE TITLE
tour: Rather than naming the method “Abs”, something like “Length” or “Hypotenuse” would be more easily understood by readers

### ISSUE THREAD

**Issue by gameprof** [golang/tour#546] opened 2018-07-07 11:48 UTC
Context: https://tour.golang.org/methods/1

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by ALTree** [comment] 2018-07-07 14:54
Hi,

this is a dup of #536. See my comment there: https://github.com/golang/tour/issues/536#issuecomment-401058809

Closing here, since it's working as intended.

**Closed by ALTree** 2018-07-07 14:54 UTC
