### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by borgogelli** [golang/tour#864] opened 2019-12-08 11:21 UTC
Context: https://tour.golang.org/moretypes/18

The example doesn't work. Here is the error:

```
go: finding golang.org/x/tour latest
go: downloading golang.org/x/tour v0.0.0-20191204025012-2e616b842c11
go: extracting golang.org/x/tour v0.0.0-20191204025012-2e616b842c11
./prog.go:6:1: missing return at end of function
```

**Comment by ALTree** [comment] 2019-12-08 11:27
Hi,

The linked page is an exercise. The slide title is Exercise: Slices, and the text below says:

> Implement Pic. It should return a slice of length dy ...

so yes, it won't compile until you solve the exercise by implementing the requested function, as the error says: "missing return at end of function".

Closing here, since this is working as intended.

**Closed by ALTree** 2019-12-08 11:27 UTC

**Comment by borgogelli** [comment] 2019-12-08 11:31
Sorry and thank you for your time
