### ISSUE TITLE
tour: Page needs update for latest versions of Go, I assume

### ISSUE THREAD

**Issue by kellyfirkins** [golang/tour#635] opened 2018-10-29 02:25 UTC
First bug report here and should be fairly straight-forward. Tough for me to describe too much as I'm learning still...
-----------
Context: https://tour.golang.org/methods/22

1) Unsure of Go Version, it's the one being hosted for the tour. 
2) macOS 10.14
3) Ran the default code in the tour, but didn't get the end result, instead ended up with this error below.

prog.go:10:26: cannot use MyReader literal (type MyReader) as type io.Reader in argument to reader.Validate:
	MyReader does not implement io.Reader (missing Read method)

**Comment by ALTree** [comment] 2018-11-05 17:43
As @Vedarth correctly pointed out, at that page there's an exercise. The code is just a stub, the `Reader` needs to be implemented by the reader, as the `TODO` in the code also says. I'm closing this issue, since it's working as intended.

**Closed by ALTree** 2018-11-05 17:43 UTC
