### ISSUE TITLE
in a map, why there has to be a comma for the last or the only element?

### ISSUE THREAD

**Issue by paperx123** [golang/tour#463] opened 2018-04-17 06:26 UTC
Context: https://tour.golang.org/moretypes/21

**Comment by bgadrian** [comment] 2018-06-27 21:49
It doesn't, but if you remove the comma you have to bring the closing bracket to the same line`}`, otherwise the "compiler" doesn't know what should be next.

**Comment by ALTree** [comment] 2018-06-28 13:11
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-06-28 13:11 UTC
