### ISSUE TITLE
tour: Explain slice's semicolon operator's 1st second parameters

### ISSUE THREAD

**Issue by tomcam** [golang/tour#177] opened 2017-03-07 17:31 UTC
Context: https://tour.golang.org/moretypes/8

Crap! I clicked some button too early. Was updating title but wasn't finished, and can't see a way to edit the title or make this damn thing go away. OK, here's what's bugging me.

I would like a short explanation of the 2nd parameter of the slice notation. It is not intuitive to me as an experienced programmer used to 0-based indices. This prints [Paul George] but I'd like a brief explanation on the left side as to why it doesn't display Ringo too.

	names := [4]string{
		"John",
		"Paul",
		"George",
		"Ringo",
	}
	fmt.Println(names)

**Comment by robphoenix** [comment] 2017-06-09 14:48
I believe this is related to , if not a duplicate of, https://github.com/golang/tour/issues/66, https://github.com/golang/tour/issues/67 & https://github.com/golang/tour/issues/68 and therefore this CL is relevant: https://go-review.googlesource.com/c/44930/ which adds the following to the explanation at https://tour.golang.org/moretypes/7:

> It has a simple form that specifies a low and high bound:

    a[low : high]

> The _indices_ `low` and `high` select which elements of array `a` appear in the result.
> The result has indices starting at `low` and length equal to `high - low`.

What do you think @tomcam?

**Closed** 2017-06-27 23:50 UTC
