### ISSUE TITLE
tour: cannot allocate memory

### ISSUE THREAD

**Issue by bwjjohnson** [golang/tour#519] opened 2018-06-13 07:13 UTC
Context: https://tour.golang.org/concurrency/4

In this slide I expected the code sample to work right unmodified, but I got a "cannot allocate memory" error.

**Comment by bgadrian** [comment] 2018-06-13 16:52
It seems a duplicate of https://github.com/golang/tour/issues/512

**Comment by ALTree** [comment] 2018-08-11 10:46
Closing as a dup of  #541

**Closed by ALTree** 2018-08-11 10:46 UTC
