### ISSUE TITLE
tour: result append.go

### ISSUE THREAD

**Issue by mreyc** [golang/tour#108] opened 2016-11-15 12:32 UTC
Context: https://tour.golang.org/moretypes/15

 append.go returns,

len=0 cap=0 []
len=1 cap=2 [0] <--- I think It is incorrect. cap must to be 1
len=2 cap=2 [0 1]
len=5 cap=8 [0 1 2 3 4]

Thanks.

**Comment by Numbluk** [comment] 2016-11-22 06:03
This is actually correct. Go internally increases the underlying size of the array *if it is smaller than the slice you need* based on 2<sup>n</sup>.

So, once the first value is appended, the capacity is 2<sup>1</sup> or 2. 

Here is an example based on the Tour. Look at how each time you `append` values that are larger than the capacity, Go increases the size of the underlying array based on 2<sup>n</sup>:

```go
var s []int
printSlice(s) // len=0 cap=0 []

s = append(s, 3)
printSlice(s) // len=1 cap=2 [1]

s = append(s, 1, 2)
printSlice(s) // len=3 cap=4 [1 2 3]

s = append(s, 2, 3, 4)
printSlice(s) // len=5 cap=8 [1 2 3 4 5]
```

**Comment by mreyc** [comment] 2016-11-22 08:47
Thanks Numbluk for reply, but I don't  know why I don't see this behavior on my computer:

~~~
u@u1404:~/work$ cat t1.go
package main

import "fmt"

func main() {
        var s []int
        printSlice(s)

        // append works on nil slices.
        s = append(s, 0)
        printSlice(s)

        // The slice grows as needed.
        s = append(s, 1)
        printSlice(s)

        // We can add more than one element at a time.
        s = append(s, 2, 3, 4)
        printSlice(s)
}

func printSlice(s []int) {
        fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}
u@u1404:~/work$ go build t1.go
u@u1404:~/work$ ./t1
len=0 cap=0 []
len=1 cap=1 [0]
len=2 cap=2 [0 1]
len=5 cap=6 [0 1 2 3 4]
u@u1404:~/work$
~~~


Regards.

**Comment by gregl83** [comment] 2017-04-09 16:27
I can reproduce what @mreyc is seeing.

*./append.go*
```
package main

import "fmt"

func main() {
	var s []int
	printSlice(s)

	// append works on nil slices.
	s = append(s, 0)
	printSlice(s)

	// The slice grows as needed.
	s = append(s, 1)
	printSlice(s)

	// We can add more than one element at a time.
	s = append(s, 2, 3, 4)
	printSlice(s)
}

func printSlice(s []int) {
	fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}
```

*go run ./append.go*
```
len=0 cap=0 []
len=1 cap=1 [0]
len=2 cap=2 [0 1]
len=5 cap=6 [0 1 2 3 4]
```
`go version go1.6.3 linux/amd64`

Note: when I remove the `4` from the last append statement and run in the playground I get the expected output.

**Comment by gregl83** [comment] 2017-04-09 16:48
Tried the same code in golang's official alpine container.

`sudo docker run -it --rm golang:1.8.1-alpine /bin/ash`

*/go/src # go run append.go *
```
len=0 cap=0 []
len=1 cap=1 [0]
len=2 cap=2 [0 1]
len=5 cap=6 [0 1 2 3 4]
```

**Comment by robphoenix** [comment] 2017-06-06 16:04
This is a duplicate of https://github.com/golang/tour/issues/102

There is an explanation as to why here: https://stackoverflow.com/questions/38573983/capacity-of-slices-in-go
From that post:
>how much the capacity of the slice is expanded by isn't mentioned in the specification and different versions of Go (or different implementations, or the same version on different architectures, etc.) can expand the slice by different amounts.

Hope that helps @mreyc

**Comment by ALTree** [comment] 2018-06-28 16:03
Yep, this is expected. It's an implementation detail. Closing this issue.

**Closed by ALTree** 2018-06-28 16:03 UTC
