### ISSUE TITLE
tour: Out of memory returned from server

### ISSUE THREAD

**Issue by nickshanks** [golang/tour#522] opened 2018-06-14 09:49 UTC
Context: https://tour.golang.org/flowcontrol/5

Result: "fatal error: runtime: out of memory"
When running code:

```go
package main

import (
	"fmt"
	"math"
)

func sqrt(x float64) string {
	if x < 0 {
		return sqrt(-x) + "i"
	}
	return fmt.Sprint(math.Sqrt(x))
}

func main() {
	fmt.Println(sqrt(2), sqrt(-4))
}
```

Removing the minus sign from the `main()` function's call to `sqrt(-4)` fixes it

**Comment by bgadrian** [comment] 2018-06-14 21:22
Duplicate of https://github.com/golang/tour/issues/521

**Comment by ALTree** [comment] 2018-08-11 10:45
Closing as a dup of  #541

**Closed by ALTree** 2018-08-11 10:45 UTC
