### ISSUE TITLE
Wrong statement about pointer indirection

### ISSUE THREAD

**Issue by rafialhamd** [golang/tour#604] opened 2018-09-12 14:23 UTC
Context: https://tour.golang.org/methods/7

> var v Vertex
> fmt.Println(v.Abs()) // OK
> p := &v
> fmt.Println(p.Abs()) // OK

>  In this case, the method call p.Abs() is interpreted as (_*p_).Abs().

The *above* statement to be changed to:

 **In this case, the method call p.Abs() is interpreted as (_&p_).Abs().**

**Comment by ALTree** [comment] 2018-09-16 10:55
Thanks for the report.

The text is correct as it is. When `p` is a pointer, `p.Abs()` will dereference the pointer, and then call the `Abs` method. The fact that `p` is dereferenced makes the expression equivalent to `*p`.

Closing here, since it's not a bug.

**Closed by ALTree** 2018-09-16 10:55 UTC

**Comment by DrH97** [comment] 2021-11-18 09:33
Quick question if I may,
Please excuse the ignorance.

Just getting started with Go and was wondering.
Isn't * used for assignment while & used to reference a pointer?

Also, in https://tour.golang.org/methods/6
you use `v.Scale(5) as (&v).Scale(5)`

while in https://tour.golang.org/methods/7
you use `p.Abs() is interpreted as (*p).Abs()`

Are they one and the same?
