### ISSUE TITLE
tour: Better basic explanation of slice syntax: say "elements xxx of array" not, "first n elements of array"

### ISSUE THREAD

**Issue by rfay** [golang/tour#209] opened 2017-04-30 02:16 UTC
Context: https://tour.golang.org/moretypes/7

Change the title above to describe your issue and add your feedback here, including code if necessary

Instead of "This expression creates a slice of the first five elements of the array a:" please say "This expression creates a slice containing elements 0 through 4 of the array a:". Then maybe explain why a[0:5] doesn't include element 5 of the array as would be expected, but only elements 0-4.

Thanks!

**Comment by rfay** [comment] 2017-05-06 01:55
The blog [Go slices Usage and Internals](https://blog.golang.org/go-slices-usage-and-internals) has much better usage around this:

> ... Slicing is done by specifying a **half-open range** with two indices separated by a colon. **For example, the expression b[1:4] creates a slice including elements 1 through 3 of b (the indices of the resulting slice will be 0 through 2).**

>`
b := []byte{'g', 'o', 'l', 'a', 'n', 'g'}
// b[1:4] == []byte{'o', 'l', 'a'}, sharing the same storage as b
`

Anyway, it's really important to get across wha the "half-open range" with indices means - it certainly doesn't mean as the [tour page says]() "a[0:5] creates a slice of the first five elements of the array a:". At least using a number other than 5 for the second item in the range will help a lot. And starting with something other than 0 will help a lot too.

**Comment by robphoenix** [comment] 2017-06-09 14:44
I believe this is related to , if not a duplicate of, https://github.com/golang/tour/issues/66, https://github.com/golang/tour/issues/67 & https://github.com/golang/tour/issues/68
and therefore this CL is relevant: https://go-review.googlesource.com/c/44930/ which adds the following to the explanation at https://tour.golang.org/moretypes/7:

> It has a simple form that specifies a low and high bound:

    a[low : high]

> The _indices_ `low` and `high` select which elements of array `a` appear in the result.
> The result has indices starting at `low` and length equal to `high - low`.

What do you think @rfay?

**Comment by rfay** [comment] 2017-06-09 22:49
Yes, this is a duplicate of those others.

No, the proposed CL doesn't really quite solve this problem because it doesn't explain in plain language the half-open range, and it needs to give an example that is not misleading. It could give a slice that does *not* start with 0 and then show an example of what shows up in `a[low : high]` in that case.

**Comment by robphoenix** [comment] 2017-06-12 10:15
I've updated the CL, changing the range to start with a different index than *0* and including an explanation of the half-open range.

**Comment by rfay** [comment] 2017-06-12 14:18
You're awesome, significantly improved, thanks!

I would still say that the phrase "The _indices_ `low` and `high` select which elements of
array `a` appear in the result. " is quite misleading and people will skim it and misunderstand. Maybe "The `low` index specifies the first included element and the `high` index specifies the element just past the last included element" ?

The fault here of course is that the creators of slices were thinking they were talking only to mathematicians and set-theoreticians, and missed the fact that people have used other computer languages before :)

**Comment by robphoenix** [comment] 2017-06-12 15:25
No worries :smile: Thankyou for the feedback!

I see what you're saying, but it's a different explanation of the slice syntax. It comes from the spec [here](https://golang.org/ref/spec#Slice_expressions) and describes the slice as having a start index, `low`, and the end of the slice is defined by how long it is, the length being `high - low`. So in the case of `a[2:7]` the slice starts at index `2` and is length `7 - 2`, so has 5 elements, ending at index `6`. I'm not sure I agree it's misleading, as the indices do select which elements appear in the slice, rather a different explanation, though equally valid, and some may find one explanation easier or more memorable than the other.
I'll wait and see what comment the CL gets from the Go team.
Maybe @adg or @bradfitz have an opinion?

**Closed** 2017-06-27 23:50 UTC

**Comment by robphoenix** [comment] 2017-06-30 10:08
I realise this is closed now and the CL merged, but I'd be interested to hear your impression of how this reads now @rfay https://github.com/golang/tour/commit/d1a15fa4af5ddb680c3d8876793f1723e1babea2
In the end I think you were right about using "The indices low and high select which elements of
array a appear in the result. " and using the half-open syntax was much clearer than my original explanation. So thanks for opening this issue and providing feedback on the CL, much appreciated. :+1:

**Comment by rfay** [comment] 2017-07-03 15:53
I think it's a pretty impressive improvement, thanks so much! I worry just a little that people who are new to 0-based arrays might stumble on "elements 1 through 3 of `a`", but hopefully they're farther along than that by the time they get here.

Thanks for the good work!
