### ISSUE TITLE
tour: No output on if-with-short-statement

### ISSUE THREAD

**Issue by bab9e9** [golang/tour#891] opened 2020-01-23 16:43 UTC
Context: https://tour.golang.org/flowcontrol/6

The output area flickers, but I only get "Program exited." This occurs with Firefox, Chrome and Edge.

**Comment by JuanBesa** [comment] 2020-01-27 13:33
The issue is that the main function is
`func main() {
	fmt.Println(
		pow(3, 2, 10),
		pow(3, 3, 20),
	)
}`

And it should be:

`func main() {
	fmt.Println(
		pow(3, 2, 10.0),
		pow(3, 3, 20.0),
	)
}
`

To math the function : `func pow(x, n, lim float64) float64 `

**Comment by ALTree** [comment] 2020-01-27 13:39
@JuanBesa No, the call is correct. 10 and 20 are untyped constants, they can be used for a float64 parameters.

The tour backend caches programs and an issue with the cache is causing these no-output problems. If you change the program (no matter how) it'll bypass the cache and show output.

**Comment by ALTree** [comment] 2020-02-03 12:45
There was a caching issues with the playground (which stores the tour programs); which is now fixed. Closing here.

**Closed by ALTree** 2020-02-03 12:45 UTC
