### ISSUE TITLE
`tour` is broken

### ISSUE THREAD

**Issue by bencodesall** [golang/tour#1203] opened 2021-06-03 06:35 UTC
```bash
╰─ go install golang.org/x/tour@latest  
go install golang.org/x/tour@latest: module golang.org/x/tour@latest found (v0.1.0), but does not contain package golang.org/x/tour
```

Looking at README.md shows
```bash
╰─ cat README.md 
# Go Tour

The actual web pages for
“A Tour of Go” moved to [golang.org/x/website](https://golang.org/x/website).

This repo still holds the supporting packages like
[golang.org/x/tour/pic](https://golang.org/x/tour/pic).
```

`golang/x/website` is no help since all it does is spin up the website locally. Tour link is to the live golang.org tour site. Readme and docs are not helpful in this regard for getting the tour installed and running locally.

**Comment by bencodesall** [comment] 2021-06-03 12:31
Is this no longer the case?
>This tour is also available as a stand-alone program that you can use without access to the internet. It builds and runs the code samples on your own machine.
>
>To run the tour locally, you'll need to first install Go and then run:
>
>`go get golang.org/x/tour`
>This will place a tour binary in your workspace's bin directory. When you run the tour program, it will open a web browser displaying your local version of the tour.

**Comment by arl** [comment] 2021-06-04 09:34
@bencodesall This works for me to spin up the tour locally:

```sh
$ go install golang.org/x/website/tour@latest
```

Then
```sh
$ tour
2021/06/04 11:31:12 Serving content from /home/aurelien/godev/pkg/mod/golang.org/x/website/tour@v0.0.0-20210603204035-9478f6c83f66
2021/06/04 11:31:12 A browser window should open. If not, please visit http://127.0.0.1:3999
2021/06/04 11:31:13 accepting connection from: 127.0.0.1:43102

```

But I agree with you, this is not what is shown in [tour.golang.org/welcome/3](https://tour.golang.org/welcome/3) and is quite confusing for newcomers which want to run the tour locally.

**Comment by ALTree** [comment] 2021-06-09 11:56
Yep. This was caused by 241d4738f53e9d144c5b601f4f579778859d6847. This repository no longer has the tour content, it's all in x/website now. So go-getting `golang/x/tour` does nothing, you need to get the module from `golang.org/x/website/tour`, as @arl mentioned.

**Comment by sagar23sj** [comment] 2021-06-10 06:27
Hi @ALTree. Earlier i had contributed to some of the issues on the tour repo which are not merged yet. Since tour repo is moved to golang.org/x/website/tour, should I create the issues on the new repo and fix them there only?

**Comment by ALTree** [comment] 2021-06-11 16:13
Yeah, probably. The content is no longer there so these patches will cause a merge conflict (and not one you can resolve, since the content is now in another repository).

**Comment by ALTree** [comment] 2021-06-22 08:20
I sent [CL 326330](https://go-review.googlesource.com/c/website/+/326330) for this (not sure why the gopherbot hasn't linked it here).

**Comment by arl** [comment] 2021-06-22 08:24
Thanks @ALTree . I also have a change for this but wasn't able to commit it, i don't remember the details but I guess I wasn't able to setup codereview correctly. In a nutshell, which directory did you clone?

**Comment by ALTree** [comment] 2021-06-22 08:40
The new workflow is that you clone https://github.com/golang/website and then change the tour content inside the `tour` directory. Not sure about gerrit, it just works for me.

**Comment by sagar23sj** [comment] 2021-06-22 08:54
Hi @ALTree. I also tried fixing this issue in some other PR related to issue #1096. 
https://github.com/golang/website/pull/63.
So, should I remove the changes specific to this issue or make changes similar to the PR you just mentioned.

Thanks

**Comment by ALTree** [comment] 2021-06-22 11:30
I'd wait a while to see if my change is merged and then rebase your change.

**Comment by lijhj** [comment] 2021-06-24 09:47
> ```shell
> $ go install golang.org/x/website/tour@latest
> ```

Thanks. It works but install on ~/go/bin/tour

I remember that the following steps worked before. 
It does not work now. Does it mean that the tour repo does not contain the full source files or what?

```
$ git clone https://github.com/golang/tour
$ cd tour
$ go build .    ## it worked before
no Go files in /home/ljh/Downloads/tour
$
```

**Comment by lijhj** [comment] 2021-06-24 09:47
> ```shell
> $ go install golang.org/x/website/tour@latest
> ```

Thanks. It works but install on ~/go/bin/tour

I remember that the following steps worked before. 
It does not work now. Does it mean that the tour repo does not contain the full source files or what?

```
$ git clone https://github.com/golang/tour
$ cd tour
$ go build .    ## it worked before
no Go files in /home/ljh/Downloads/tour
$
```

**Comment by lijhj** [comment] 2021-06-24 11:23
It can bind an existing LAN ip of the localhost. I remember that it could be a new ip before.

$ ip addr | grep 192
    inet 192.168.1.6/24 brd 192.168.1.255 scope global dynamic noprefixroute ens33
$ 
$ tour --http 192.168.1.6:3999

**Closed** 2021-07-17 16:35 UTC
Labels: NeedsFix

**Comment by mikeaustin** [comment] 2021-11-30 19:58
Not sure if this is still the same issue, but the online tour is definitely broken. I remember using it months ago and enjoying stepping through each slide and experimenting with code. Now, I get "Error communicating with remote server" and dead links.

https://go.dev/learn
Tour of Go > https://go.dev/tour
https://go.dev/tour/welcome/1
  Run > Error communicating with remote server.
Congratulations https://go.dev/tour/welcome/5
  Both "A Tour of Go" and "next lesson" links don't do anything
