### ISSUE TITLE
tour: Provided codes in page "Appending to a slice" returns nothing

### ISSUE THREAD

**Issue by zqian1726** [golang/tour#385] opened 2018-01-18 06:10 UTC
Context: https://tour.golang.org/moretypes/15

Details: If I use the exact same content provided in the tour and run it in the playground, it returns nothing but just a line of "Program exited."

The provided code are:
```
package main

import "fmt"

func main() {
	var s []int
	printSlice(s)

	// append works on nil slices.
	s = append(s, 0)
	printSlice(s)

	// The slice grows as needed.
	s = append(s, 1)
	printSlice(s)

	// We can add more than one element at a time.
	s = append(s, 2, 3, 4)
	printSlice(s)
}

func printSlice(s []int) {
	fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}

```

However, if I change any character in the code, even just removing the last new line or modify any character in a comment, it will work well.

I believe this is a caching issue on the server, that the results of the default codes are cached somewhere with an empty result.

Please kindly take a look and refresh the cache.

**Comment by andybons** [comment] 2018-08-10 20:38
Duplicate of #541

**Closed by andybons** 2018-08-10 20:38 UTC
