### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by tartrsn** [golang/tour#949] opened 2020-04-12 17:51 UTC
Context: https://tour.golang.org/basics/6

We've got

```
	a, b := swap("hello", "world")
	fmt.Println(a, b)
```

In main, however it doesn't print anything

**Comment by tangsaidi** [comment] 2020-04-21 20:49
I was not able to reproduce the bug

It prints out `world hello` for me. Could you provide more context

**Comment by ALTree** [comment] 2020-05-09 15:47
There were some server-side issue 2 weeks ago that could cause no output, but they should be fixed now. Closing here.

**Closed by ALTree** 2020-05-09 15:47 UTC
