### ISSUE TITLE
tour: [Slices Capacity is wrong]

### ISSUE THREAD

**Issue by ShankarSG** [golang/tour#800] opened 2019-07-21 11:34 UTC
Context: https://tour.golang.org/moretypes/15

The output of code on the above page is as below, and It seems it is printing wrong cap value in the second line.

len=0 cap=0 []
**len=1 cap=2 [0]**
len=2 cap=2 [0 1]
len=5 cap=8 [0 1 2 3 4]

when I run the same code in VSCode, it is printing as below,

len=0 cap=0 []
**len=1 cap=1 [0]**
len=2 cap=2 [0 1]
len=5 cap=6 [0 1 2 3 4]

**Comment by ALTree** [comment] 2019-07-21 16:00
The value of `cap` grows in a way that is platform-dependent. On 32-bits systems (like the one the playground runs on), it can grows differently that how it does on your 64-bit system.

Closing here, since this is not a bug.

**Closed by ALTree** 2019-07-21 16:00 UTC
