### ISSUE TITLE
[Need help] Question regarding Interface

### ISSUE THREAD

**Issue by afzal442** [golang/tour#1242] opened 2021-09-09 12:41 UTC
Not able to access multiple methods inside an interface

```package main

type I interface {
	M()
	N()
}
type F int
type X string

func (f F) M() {
}

func (x X) N() {
}

func main() {
	var i I
	i = F(42)
	i.M()
	i = X("hry")
	i.N()
}
```
error: 
./prog.go:18:4: cannot use F(42) (type F) as type I in assignment:
	F does not implement I (missing N method)
./prog.go:20:4: cannot use X("hry") (type X) as type I in assignment:
	X does not implement I (missing M method)

Will it be possible to call two methods inside an interface?

**Comment by ALTree** [comment] 2021-09-09 13:08
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2021-09-09 13:08 UTC

**Comment by afzal442** [comment] 2021-09-09 13:37
Thanks
