### ISSUE TITLE
tour: Incorrect word

### ISSUE THREAD

**Issue by mcjbuckley** [golang/tour#388] opened 2018-01-22 14:21 UTC
Context: https://tour.golang.org/moretypes/10

The second line is: 'The default is zero for the low bound and the length of the **slice** for the high bound.'
It should actually read: 'The default is zero for the low bound and the length of the **array** for the high bound.'
(Or the capacity of the slice)

**Comment by tauki** [comment] 2018-01-28 06:26
Hi, slice in go is a data structure so in this context the line is correct. Slice is dynamically-sized in other sense, flexible. So there's no real capacity for a slice. The size of a slice determines the number of elements the size is holding at the moment.
@mcjbuckley, If you think it answers your question or solves the issue, you may close it or, help me better understand from your point of view.

**Comment by ALTree** [comment] 2018-07-02 12:16
> length of the slice for the high bound.

This is correct, and changing it to " length of the array" would be wrong, because the backing array may be longer that the slice, but in the example `len(s)` will print 1, not 4 (which is the length of the backing array). Closing.

**Closed by ALTree** 2018-07-02 12:16 UTC

**Comment by crisman** [comment] 2023-03-10 01:32
Duplicate of golang/tour#182
