### ISSUE TITLE
tour: looks like you can use single quote strings of single character length in function

### ISSUE THREAD

**Issue by jrhennessy** [golang/tour#504] opened 2018-06-07 13:54 UTC
Context: https://tour.golang.org/basics/5

The example if for a function that adds 2 ints, but i am able to pass into x or y a single quote string ex: 'a' and it will treat it as it's ascii int value and add it. Should this be allowed? Double quotes: "a" for example does not work and correctly errors because the type is not int

**Comment by bgadrian** [comment] 2018-06-07 22:38
Single quotes means it's a Rune (like a Char in other languages, for for UNICODE). 
Rune is implemented in Go as an alias for int32 see https://golang.org/pkg/builtin/#rune 

So yes it should work like that.

Double quotes literal are strings, that cannot be converted to 1 value of integer.

**Comment by ALTree** [comment] 2018-06-28 13:11
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-06-28 13:11 UTC
