### ISSUE TITLE
tour: Syntax by default is off and button are backwards?

### ISSUE THREAD

**Issue by tamaw** [golang/tour#552] opened 2018-07-12 01:46 UTC
Context: https://tour.golang.org/welcome/4

**Steps to reproduce:**
Start new private browsing session (previous state is saved)
Open the tour online.
By default the syntax is off.
Click the button says "Syntax Off". 
Notice the syntax is now on.

**Browser:**
Firefox Quantum - 61.0.1 (64-bit) 
**Operating System:** 
Windows 10 version 1803 (OS Build 17134.112)

**Comment by ALTree** [comment] 2018-07-12 07:43
> By default the syntax is off.
> Click the button says "Syntax Off".
> Notice the syntax is now on.

The text on the button reflects the current status, not the action the button does.

The design of On/Off buttons is a well-known UX problem: 

https://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan

In this case I don't think it's a huge problem because you can tell whether the syntax is On or Off by looking at the code... so you don't need the text on the button, really. This is generally more of an issue when the current status is "hidden", and you look at the button to understand what the status is.

**Comment by bgadrian** [comment] 2018-07-12 15:32
yes, basically ![onoff](https://i.stack.imgur.com/LVcH6.png)

I think they can be improved in more ways
* make them look more like other popular similar buttons
* make them [toggles/checkboxes ](https://68.media.tumblr.com/41b8f2d6f2edc0b331939ff64fbb8efd/tumblr_nx4n0fffJ31uij4nfo1_500.jpg)
* change the text to call to action (Enable syntax)

But I would leave them as they are for now.

**Comment by bgadrian** [comment] 2018-07-15 20:55
Playground uses a checkbox, maybe the tour should too?

![image](https://user-images.githubusercontent.com/830001/42738303-5773608c-888a-11e8-9d58-f993743e2ff7.png)

**Comment by ALTree** [comment] 2018-07-15 22:08
> Playground uses a checkbox

Which I find super ugly.

Also it wouldn't buy us anything because as I wrote above you can tell whether the syntax is On or Off by looking at the code. What other additional information would the checkbox give you?

I'm leaning towards closing this as LAI (looking... as intended)

**Closed by ALTree** 2018-07-15 22:08 UTC
