### ISSUE TITLE
For loop error in tour

### ISSUE THREAD

**Issue by sagadsalem** [golang/tour#663] opened 2018-12-07 09:49 UTC
Context: https://tour.golang.org/flowcontrol/1

the code has error => prog.go:7:7: syntax error: unexpected comma, expecting )
```
package main

import "fmt"

func main() {
	t := []string{"g", "h", "i"}
	for(_,file) in files {
		fmt.Println(file)
	}
}
```

**Comment by ALTree** [comment] 2018-12-07 17:13
That's not the code I see on flowcontrol/1. This is the code on that slide:

```
package main

import "fmt"

func main() {
	sum := 0
	for i := 0; i < 10; i++ {
		sum += i
	}
	fmt.Println(sum)
}
```

you (or something using the same computer and browser) changed the code. The playground (used in the tour) caches modification of the code examples. Clear the cache or use the tour `reset` button to restore the original code.

Closing here, since that's not a bug.

**Closed by ALTree** 2018-12-07 17:13 UTC
