### ISSUE TITLE
tour: does not check for semicolon

### ISSUE THREAD

**Issue by riffmichael** [golang/tour#72] opened 2016-08-30 01:41 UTC
Context: https://tour.golang.org/welcome/1

I added semicolons but the code did not throw an error

**Comment by bgadrian** [comment] 2018-06-27 20:40
The semicolons are optional [see more here](https://golang.org/doc/effective_go.html#semicolons)

**Comment by ALTree** [comment] 2018-06-28 12:35
Yep, semicolons are allowed. Closing here, since it's not a bug.

**Closed by ALTree** 2018-06-28 12:35 UTC
