### ISSUE TITLE
tour: [Why does capacity change with" s = s[2:]" but not with "s = s[:0]"?]

### ISSUE THREAD

**Issue by JESii** [golang/tour#156] opened 2017-02-01 02:22 UTC
Context: https://tour.golang.org/moretypes/11

That was quite a surprise to see "s = s[:0]" leave the capacity at 6, but then to have "s = s[2:]" reduce the capacity to 4.

What's the rationale behind that?

**Comment by bgadrian** [comment] 2018-06-27 21:07
You have to understand how slices are implemented first. There is a Head (where the slice starts at, in the original array). You can move that head only forward, not backwards. 
The capacity is the distance between the Head and the end of the underlying array. 
The s[:0] slice can grow eventually back to [0:5], but s[2:] cannot move back to s[0:].

**Comment by ALTree** [comment] 2018-06-28 13:10
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-06-28 13:10 UTC
