### ISSUE TITLE
Where the code are executed?

### ISSUE THREAD

**Issue by Xieyuschen** [golang/tour#1098] opened 2020-12-17 06:00 UTC
I clone `tour` to my pc and run it successfully. When I add lines of code like `fmt.Println("Glad to see you")` and click `Run` button, it tells me  `Waiting for remote server`, and then output as I expect.
My question is that **where the code are  executed** and **how my source code in browser pass to backend**? For little experience about Js, I ask this question:(

**Comment by denglinfeng1** [comment] 2020-12-21 09:21
I love your girl friend, too.hiahiahia~~~just kidding...
I guess the code will be compiled online and execute at back-end, then view result by tcp/ip

**Comment by Xieyuschen** [comment] 2020-12-21 12:57
> I love your girl friend, too.hiahiahia~~~just kidding...
> I guess the code will be compiled online and execute at back-end, then view result by tcp/ip

They use websocket protocol to transfer go
Code, and use a go-tool called go playground as a sindbox to execute go
Code. I still confused how code are transfered by websocket and how they are returned because I know nothing about angular is

**Comment by wadhapopa** [comment] 2021-03-11 15:13
how can i use go on the first time

**Comment by ALTree** [comment] 2021-05-12 15:01
Hi, we only use the issue tracker for reporting bugs in the tour content, see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2021-05-12 15:01 UTC
