### ISSUE TITLE
tour: [Line numbers are interlaced with the program code, making it unreadable]

### ISSUE THREAD

**Issue by massivewar** [golang/tour#323] opened 2017-10-23 09:39 UTC
![line number overlay](https://user-images.githubusercontent.com/10276519/31882341-12f5ec40-b7ac-11e7-974d-b897e83e0016.png)
Context: https://tour.golang.org/basics/16

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by shawnthroop** [comment] 2017-10-23 11:22
Same for me, context: https://tour.golang.org/moretypes/19

**Comment by massivewar** [comment] 2017-10-23 11:26
I just use the local version now:

$ gotour

Hasn't solved the problem but I'm able to go through the tutorials.

**Comment by karlcow** [comment] 2017-10-24 01:50
We found out in webcompat.com 
https://webcompat.com/issues/12718

there 's a missing `position: absolute` or `relative` on each line in the style attribute.

**Comment by jeffallen** [comment] 2017-10-25 11:39
The content being served from https://tour.golang.org/static/lib/codemirror/lib/codemirror.css
is not the same as https://github.com/golang/tour/blob/master/static/lib/codemirror/lib/codemirror.css right now.

If you try to reproduce this problem using a local gotour, you won't be able to see it because of this.

So the first problem is that the production gotour is using code that's not checked into Github. And the second problem is that the codemirror.css that's not checked in is missing the position style attribute as mentioned by @karlcow .

**Comment by rebellionyu** [comment] 2017-10-25 15:35
I have this problem too. But it worked properly a few days ago.

**Comment by bigunyak** [comment] 2017-10-26 16:47
Have the same problem for a couple of days now.
Must be an easy fix, why taking so long?

**Comment by jeffallen** [comment] 2017-10-26 18:26
I would guess because of 1.9.2. But now maybe we can get some help from @Churchill who touched CodeMirror last?

**Comment by shurcooL** [comment] 2017-10-26 22:43
I can't reproduce this in Chrome 62.0.3202.62 on macOS 10.13. When I visit https://tour.golang.org/basics/16, it looks normal to me:

![image](https://user-images.githubusercontent.com/1924134/32080421-8493c9ac-ba7d-11e7-84fd-080b616f5905.png)

Has something changed? Otherwise, how can I reproduce this?

**Comment by karlcow** [comment] 2017-10-26 23:42
Yes it has been fixed. Both in Chrome and Safari, the same working layout.

**Comment by resurtm** [comment] 2017-10-27 06:25
I confirm that too. Works for me now (Chrome 62 too).

**Comment by shurcooL** [comment] 2017-10-27 06:38
I'll close this since it's resolved now. Please let us know if it comes up again.

**Closed by shurcooL** 2017-10-27 06:38 UTC
