### ISSUE TITLE
tour: 'Appending to a slice' does no appending!

### ISSUE THREAD

**Issue by dstockton** [golang/tour#802] opened 2019-07-23 08:56 UTC
Context: https://tour.golang.org/moretypes/15

The example code does not call the described function (append)!

```
package main

import (
	"fmt"
	"strings"
)

func main() {
	x := "us-west-1a,a,us-west-1b,b,us-west-1a,a,us-west-1b,b"
	y := strings.Split(x, ",")
	for i, s := range y {
		if i%2 != 0 {
			fmt.Println("Result", i/2+1, y[i-1], s)
		}
	}

}
```

**Comment by ALTree** [comment] 2019-07-25 06:44
> The example code does not call the described function (append)!

Actually it does, but not in your browser.

The code in the tour is editable and the changes are cached locally. Someone else changed the code to experiment and now you're seeing their changes. If you press the reset button under the code, the code will be restored to its original state, which is this:

```
package main

import "fmt"

func main() {
	var s []int
	printSlice(s)

	// append works on nil slices.
	s = append(s, 0)
	printSlice(s)

	// The slice grows as needed.
	s = append(s, 1)
	printSlice(s)

	// We can add more than one element at a time.
	s = append(s, 2, 3, 4)
	printSlice(s)
}

func printSlice(s []int) {
	fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}
```

Closing here, since this is not a bug.

**Closed by ALTree** 2019-07-25 06:44 UTC
