### ISSUE TITLE
tour: Code cannot be run

### ISSUE THREAD

**Issue by Thoemmeli** [golang/tour#847] opened 2019-11-13 13:24 UTC
Context: https://tour.golang.org/moretypes/26

The code provided in the sample doesn't run. I get the following message:

> ./prog.go:8:1: missing return at end of function

This is the code on the page:
```
package main

import "fmt"

// fibonacci is a function that returns
// a function that returns an int.
func fibonacci() func() int {
}

func main() {
	f := fibonacci()
	for i := 0; i < 10; i++ {
		fmt.Println(f())
	}
}
```

**Comment by ALTree** [comment] 2019-11-13 13:35
Hi, the linked page is an exercise. The slide title is **Exercise: Fibonacci closure**, and the text below says:

> Implement a fibonacci function that returns a function

so yes, it won't compile until you solve the exercise : )

Closing here, since this is working as intended.

**Closed by ALTree** 2019-11-13 13:35 UTC
