### ISSUE TITLE
tour: "go tool tour" doesn't seem to work now?

### ISSUE THREAD

**Issue by seebs-markley** [golang/tour#153] opened 2017-01-30 19:56 UTC
Context: https://tour.golang.org/welcome/3

$ go version
go version go1.7.4 darwin/amd64
$ go tool tour
go tool: no such tool "tour"

**Comment by subbu05** [comment] 2017-02-04 03:13
go version
go version go1.7.5 darwin/amd64
go tool tour
go tool: no such tool "tour"

**Comment by alebaffa** [comment] 2017-04-04 20:28
`go too tour` is now available in go1.8. This issue can be closed.

**Comment by lengocgiang** [comment] 2017-05-06 15:28
Just try
`gotour`

**Comment by bgadrian** [comment] 2018-06-27 22:23
Go tour install issues, duplicate of #8, probably [this comment](https://github.com/golang/tour/issues/8#issuecomment-306527940) is what are you looking for.

**Comment by ALTree** [comment] 2018-07-04 09:49
Closing as a dup of #8.

**Closed by ALTree** 2018-07-04 09:49 UTC
