### ISSUE TITLE
tour: Sample code does not illustrate what text describes

### ISSUE THREAD

**Issue by GameMaker** [golang/tour#1019] opened 2020-08-13 20:58 UTC
Context: https://tour.golang.org/moretypes/4

Short version: line 12 should be `p := &v`

This page explains that if you have a pointer to a struct, you can access its fields without dereferencing the pointer.
However the sample code does not appear to create a pointer to a struct.

Either it should be &v, or all assignments of structs to new variables implies it's a pointer, which is opaque for a new user. Given this is the tour of go, a simpler example would probably be more helpful.

**Comment by ALTree** [comment] 2020-08-13 21:06
>Short version: line 12 should be p := &v 

Line 12 *is* `p := &v`. 

Click the `Reset` button on the bottom right to reset the code example to its original state (it's editable).

**Comment by GameMaker** [comment] 2020-08-13 22:57
Ok, super bizarre. No idea how my sample code got into that state - I have a screencap of it without the ampersand, and did not edit it.

Yeah, see, as a test, I just dragged the "https://tour.golang.org/moretypes/4" url from THIS page (#1019) to a new tab, and there is NO ampersand. Fresh reload.

I guess the issue is: Sometimes the sample code loads without an ampersand on line 12.

This has happened to me twice today, on the same machine, but with two different chrome users logged in.

![noamp](https://user-images.githubusercontent.com/1099635/90195130-9180a880-dd7d-11ea-85dc-86c9be55fc52.png)

**Comment by ALTree** [comment] 2020-08-31 16:33
I see, but it's definitely caused by caching on the browser side: the code without `&` simply does not exists on the server. In general cleaning the cache may help. Closing here since I don't think this is a bug in the tour.

**Closed by ALTree** 2020-08-31 16:33 UTC
