### ISSUE TITLE
tour: Buffered Channels error message incorrect

### ISSUE THREAD

**Issue by acscott** [golang/tour#139] opened 2017-01-07 18:12 UTC
Context: https://tour.golang.org/concurrency/3

The error message says "fatal error: all goroutines are asleep - deadlock!"

This is not a deadlock.  Underneath, the runtime may have locks on the channel and buffer, but at the code level there are no deadlocks.  So this spreads a false definition of a deadlock to budding developers.  In other words, we have not coded any locks here.  We are simply waiting for the buffer in the channel to be cleared.  

To improve this error, you could say "deadlock underneath: " and indicate what two threads are waiting on each other's locks to be released.  Or do away with the term "deadlock" and call it something like "infinite wait".

**Comment by ALTree** [comment] 2020-05-09 16:03
> we have not coded any locks here

I think the error message is fine. A deadlock, in general, needs not to be caused by explicit lock. For example the en.wiki page says:

> In concurrent computing, a deadlock is a state in which each member of a group is waiting for another member, including itself, to take action [...]

which applies here. Moreover that message comes from the runtime, it has nothing to do with the tour itself, so this should be raised as a golang/go issue.

Closing here, since this is not a tour issue.

**Closed by ALTree** 2020-05-09 16:03 UTC
