### ISSUE TITLE
tour: [cannot allocate memory error]

### ISSUE THREAD

**Issue by johnbalvin** [golang/tour#528] opened 2018-06-20 06:09 UTC
Context: https://tour.golang.org/concurrency/4

When running on the web page I get this error:
 /usr/local/go/src/sync/pool.go:9:2: read /usr/local/go/src/runtime/symtab_test.go: read /usr/local/go/src/runtime/symtab_test.go: cannot allocate memory

**Comment by bgadrian** [comment] 2018-06-20 07:14
I think is a duplicate of https://github.com/golang/tour/issues/512

**Comment by ALTree** [comment] 2018-08-11 10:46
Closing as a dup of  #541

**Closed by ALTree** 2018-08-11 10:46 UTC
