### ISSUE TITLE
tour: Pi is already capitalized and exported on page 3

### ISSUE THREAD

**Issue by seandhaynes** [golang/tour#793] opened 2019-06-23 21:21 UTC
Hey!

Context: https://tour.golang.org/basics/3

After reading the documentation on that page (around exported names), it seems to explicitly expect the Pi function not to be exported:
```
Run the code. Notice the error message.
```

However, the respective code is already correctly capitalized:
```
fmt.Println(math.Pi)
```
Unless I'm missing something, could we please change either the documentation to tell people to play around and change casing, or amend the code so that ```math.Pi``` is actually ```math.pi``` So that people see an error?

**Comment by littlepiggy03** [comment] 2019-06-29 09:10
Well, on my first visit, the page showed `fnt.Println(math.pi)`. Can you try clearing the browser cache and refreshing the page?

**Comment by ALTree** [comment] 2019-07-25 06:46
Thanks for reporting this.

The code is editable and changes are cached locally. As @littlepiggy03 said, you can press the "RESET" button under the code (or clean the cache) to restore the code's original state. Closing here, since this is working as intended.

**Closed by ALTree** 2019-07-25 06:46 UTC
