### ISSUE TITLE
tour: Mistake in slice defaults text

### ISSUE THREAD

**Issue by jolenedunne** [golang/tour#443] opened 2018-03-27 13:59 UTC
Context: https://tour.golang.org/moretypes/10

> The default is zero for the low bound and the _length of the slice_ for the high bound.

I think this should be _length of the underlying array_

**Comment by ALTree** [comment] 2018-07-04 09:18
Thanks for the report.

>  think this should be length of the underlying array

If you make the underlying array bigger (e.g. by appending 100 elements), and then re-size the slice with `s = s[1:3]`, the backing array will still be >100 in length, but in a subsequent expression `s[1:]` means "up to element 3", and not "until element 100" (or whatever the size is).

Since this is working as intended, I'm closing this issue.

**Closed by ALTree** 2018-07-04 09:18 UTC

**Comment by crisman** [comment] 2023-03-10 01:31
Duplicate of golang/tour#182
