### ISSUE TITLE
tour: Concurrency/2 throws Error

### ISSUE THREAD

**Issue by seufagner** [golang/tour#229] opened 2017-05-22 19:37 UTC
Context: https://tour.golang.org/concurrency/2

When I run the script throws error below:

tmp/sandbox380382827/main.go:11: syntax error: missing channel element type
tmp/sandbox380382827/main.go:11: non-name chan <N> on left side of :=

**Comment by kytrinyx** [comment] 2017-05-31 21:32
@seufagner Just to confirm, you're running this by clicking the "run" button on the website, right?

If you run the script on that page without any changes does it give you errors?

**Comment by ALTree** [comment] 2018-06-28 12:59
Code as it is runs fine so this must have been caused by a change in the code. Closing.

**Closed by ALTree** 2018-06-28 12:59 UTC
